#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.
COWNTER=0
while [ $COWNTER -lt 10 ]
do
	echo "Best School"
	COWNTER=$(( COWNTER +1 ))
	if [ $COWNTER -eq 9 ]
	then
		echo "Hi"
	fi
done
