#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.
COWNTER=0
while [ $COWNTER -lt 10 ]
do
	if [ $COWNTER -eq 3 ]
	then
		echo "bad luck"
	elif [ $COWNTER -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	COWNTER=$(( COWNTER +1 ))
done
